### ISSUE TITLE
Small issue with responsiveness

### ISSUE THREAD

**Issue by Levizar** [oswhyteknits/orincywhyte_frontendengineer#1]
Hello, having seen your post on LinkedIn, I noticed that small issue:

![Screenshot_20220209-002636.png](https://user-images.githubusercontent.com/52834046/153093646-cc6864be-0592-4ebf-a7c3-b8cd6577aadb.png)

Have a nice day

**Comment by oswhyteknits** [comment]
Thanks Levizar.  The issue actually is the svg. I’m building all the graphics myself so once I get that time to get in illustrator I can work on it. But while I have you here, there is another glitch (it’s minor) but I’m not sure how to fix it. It’s the nav bar burger menu. 

If you are on a laptop, the burger menu opens up in mobile view BUT if you don’t close the burger menu before stretching the screen to laptop view, the menu stays open 🤔🤔  I would do appreciate an extra eye on that. Thanks in advance. And I appreciate you checking out my project. It was a labor of love.

**Comment by Levizar** [comment]
> If you are on a laptop, the burger menu opens up in mobile view BUT if you don’t close the burger menu before stretching the screen to laptop view, the menu stays open thinkingthinking I would do appreciate an extra eye on that. Thanks in advance. And I appreciate you checking out my project. It was a labor of love.

I'm not experienced with tail-wind.
Looking at your code, I would say that you need to give different rules in your css using media queries OR to put some JS event listener and write what you want to happen when the width size changes.
